### ISSUE TITLE
parquet with s3 uri?

### ISSUE THREAD

**Issue by christine-e-smit** [intake/intake-parquet#15]
Hi! I'm sort of new to intake, so I apologize if this question has an obvious answer.

I have a bunch of parquet files sitting in s3 that aren't public. They are accessible with my AWS credentials using s3-style URIs. (E.g. s3://bucket-name/data.parquet). Is it possible to use intake-parquet with this data? I see how to do with with public URLs, but I'm stumped with s3 URIs.

Thanks!

**Comment by martindurant** [comment]
The source takes the argument `storage_options=` for all kwargs to be passed on to the storage backend, in this case s3fs. That, in turns, takes a [whole load of kwargs](https://s3fs.readthedocs.io/en/latest/api.html#s3fs.core.S3FileSystem) that you might want to set, like URL endpoint; but for auth the most important ones are key, secret, token, etc.
In practice, you usually don't need to do this, though, since you can use environment variables, files in special places, or cluster metadata to establish your credentials (see [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#configuring-credentials)).

**Comment by christine-e-smit** [comment]
Right. Okay. Yes. I'm pretty sure the AWS credentials are fine because I can run

```
df = dask.dataframe.read_parquet('s3://bucket/data.parquet')
```
without any problems. (Obviously this is not a real path!) But when my catalog looks like this:
```
plugins:
  source:
    - module: intake_parquet
sources:
  data:
    description: My wonderful data
    driver: parquet
    args:
      urlpath: 'https://bucket/data.parquet'
```
I'm getting errors that look to me as though the code is not actually getting to the parquet file. Are you saying that I need to add options under sources/data that tells the catalog to use s3fs somehow?

**Comment by martindurant** [comment]
Should be the same url
```
      urlpath: "'s3://bucket/data.parquet"
```

**Comment by christine-e-smit** [comment]
Oh! Okay. I didn't know that you could put the s3 URI under 'urlpath'. That did it. Thank you very much!
